config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'

  get 'reviews/create'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :bikes do
    resources :bookings, only: [:create, :edit, :update, :destroy]
    resources :reviews, only: [:index, :new, :create, :show]
  end

  namespace :profile do
  	resources :bikes, only: :index
    resources :bookings, only: :index
  end

  resources :users, only: :show

  mount Attachinary::Engine => "/attachinary"
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_bicycle.html.erb
<div class="encapsulate">
  <div class="place">
    <div class="stuff">
      <div id="animation">
          <div class="bike">
              <div class="bell">
                  <div class="ringer">
                      <div class="lever"></div>
                  </div>
                  <div class="audio">
                      <div></div>
                      <div></div>
                      <div></div>
                  </div>
                  <div class="stand"></div>
              </div>
              <div class="front wheel">
                  <div class="rim">
                      <div class="air"></div>
                  </div>
                  <div class="hub"></div>
                  <div class="spokes">
                      <div></div>
                      <div></div>
                      <div></div>
                      <div></div>
                      <div></div>
                      <div></div>
                      <div></div>
                      <div></div>
                  </div>
              </div>
              <div class="frame">
                  <div></div>
                  <div></div>
                  <div></div>
                  <div class="small"></div>
                  <div></div>
                  <div></div>
                  <div class="small"></div>
                  <div class="small"></div>
              </div>
              <div class="seat">
                  <div class="support"></div>
                  <div class="saddle"></div>
              </div>
              <div class="handlebars">
                  <div class="frameConnector"></div>
                  <div class="handle"></div>
              </div>
              <div class="pedals">
                  <div class="gear">
                      <div class="hub"></div>
                      <div class="struts">
                          <div></div>
                          <div></div>
                          <div></div>
                          <div></div>
                          <div></div>
                      </div>
                  </div>
                  <div class="front pedal">
                      <div class="footpad"></div>
                  </div>
                  <div class="back pedal">
                      <div class="footpad"></div>
                  </div>
              </div>
              <div class="back wheel">
                  <div class="rim">
                      <div class="air"></div>
                  </div>
                  <div class="hub"></div>
                  <div class="gear"></div>
                  <div class="spokes">
                      <div></div>
                      <div></div>
                      <div></div>
                      <div></div>
                      <div></div>
                      <div></div>
                      <div></div>
                      <div></div>
                  </div>
              </div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<div id="flash">
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer-fixed">
  <div class="wrapper-foot">
    <p>&copy; BBBikes</p>
  </div>
  <ul class="list-inline text-center">
    <li class="fa fa-youtube-square fa-lg text-center"  aria-hidden="true"></li>
    <li class="fa fa-facebook-square fa-lg text-center" aria-hidden="true"></li>
    <li class="fa fa-twitter-square fa-lg text-center" aria-hidden="true"></li>
    <li class="fa fa-instagram fa-lg text-center" aria-hidden="true"></li>
    <%= image_tag 'builtinmtl.png', id:"mtl" %>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag 'bicycle1600.png' %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
  <%= link_to t(".see_bikes", default: "View Bikes"), bikes_path, class: "btn btn-link", id: "view-bikes" %>

    <!-- Search form -->
<!--     <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

  <!-- Different navigation if login or not -->
  <% if user_signed_in? %>
    <!-- Notification -->

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% avatar_url = current_user.facebook_picture_url || current_user.photo.url(:bright_face) %>
        <% if !avatar_url.nil? %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
          <span class="fa fa-user-circle-o fa-2x" aria-hidden="true" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown" ></span>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to profile_bikes_path do %>
              <i class="fa fa-bicycle"></i> <%= t(".bike", default: "Your Bikes") %>
            <% end %>
          </li>
          <li>
            <%= link_to edit_user_registration_path do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Update your profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to profile_bookings_path do %>
              <i class="fa fa-calendar-o"></i> <%= t(".booking", default: "See your bookings") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post a bike"), new_bike_path, class: "navbar-wagon-item navbar-wagon-button", id: "post" %>

  <% else %>

    <!-- Login text link -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-button", id: "login" %>
    <%= link_to t(".sign_up", default: "Signup"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-button", id: "signup" %>
  <% end %>

</div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>